### ISSUE TITLE
pgd_attack_cifar10.py Output

### ISSUE THREAD

**Issue by Esaada** [yaodongyu/TRADES#15]
Hi , forgive me for my ignorance, I'm trying to  pgd_attack_cifar10.py, with your WideResnext, and I'm getting the following:
![image](https://user-images.githubusercontent.com/23050230/70866726-e7464c00-1f75-11ea-9d7e-d4fdc4840750.png)
 
I have a hard time to understand the results, what does each "err pdg" means?
What does the last two lines means? I mean not the names, but the values "1508", "4281"
Maybe I'm just used to top1, top5...
Thanks!

**Comment by yaodongyu** [comment]
Hi Esaada,

1. The 'err pdg' means the number of misclassified examples (which is attacked by PGD) for each mini-batch.
2. 1508' is the natural_err_total, which means the total number of misclassified clean examples for the whole test dataset (total number of test examples: 10000).
3. '4281' is the robust_err_total, which means the total number of misclassified adversarial examples (attacked by PGD) for the whole test dataset (total number of test examples: 10000).

**Comment by Esaada** [comment]
Thanks!
Just one more question where can we see it in the table:
https://github.com/yaodongyu/TRADES#white-box-leaderboard-1

**Comment by yaodongyu** [comment]
You can regard it as the fourth row of the table. As the attack result of the row of the table is the 20-step PGD attack with different attack parameters.

**Comment by Esaada** [comment]
Got it, Thanks, closing.
