### ISSUE TITLE
Unused Wide-ResNet Block sub_block1

### ISSUE THREAD

**Issue by davidstutz** [yaodongyu/TRADES#16]
Hi,

just tried out the pre-trained models and came across an unused ResNet block in your Wide ResNet: `sub_block1`. Unfortunately, the pre-trained models include parameters for this block, making it impossible to load the models using a Wide ResNet implementation that does not have `sub_block1`. 

As quick fix, I loaded the models using your Wide ResNet implementation, set `sub_block1` to a simple dummy identity layer (or any other layer without parameters) and saved them again. Afterwards, they can be loaded using an implementation without `sub_block1`.

Thought that might be interesting for others, or worth fixing (and re-uploading the models) as the unused block also incurs an unncessary memory overhead.

**Comment by yaodongyu** [comment]
Hi David,

Thanks for your suggestion, I will add another version of Wide ResNet and its corresponding pretrained checkpoint.

Thanks,
Yaodong

**Comment by yaodongyu** [comment]
Hi David, 

I added another version of Wide ResNet (```wideresnet_update.py```) which does not include the ```sub_block1```, and the pretrained model in our repo can be loaded as follows:

```
from models.wideresnet import WideResNet
from models.wideresnet_update import WideResNet as wrn_update
        
model = WideResNet().to(device)
model.load_state_dict(torch.load(args.model_path))
pretrained_dict = model.state_dict()
        
model_update = wrn_update().to(device)
model_dict = model_update.state_dict()
# 1. filter out unnecessary keys
pretrained_dict = {k: v for k, v in pretrained_dict.items() if k in model_dict}
# 2. overwrite entries in the existing state dict
model_dict.update(pretrained_dict)
# 3. load the new state dict
model_update.load_state_dict(model_dict)
```

Let me know if you have any questions.

Thanks,
Yaodong

**Comment by davidstutz** [comment]
Thanks for taking care of that. That's pretty similar to my solution and it will definitely help people avoid some memory overhead.
