### ISSUE TITLE
Submitting my result to white MNIST and CIFAR-10 leaderboards 

### ISSUE THREAD

**Issue by liuye6666** [yaodongyu/TRADES#19]
dear,yaodong yu and hongyang zhang:
   I am very happy to read such a good paper, and thank you very much for providing the white box MNIST and CIFAR-10 leaderboards. I recently（2020.8.15） submitted the results of my adversarial attack to you. If you have time, could you check my results and update the MNIST and CIFAR-10 leaderboards?
Thank you very much！
My name is ye Liu.

**Comment by hongyanz** [comment]
Hi Ye,

Neither Yaodong nor I receive your submission so far. Can you double check you have sent your submission to us with correct email address?

**Comment by liuye6666** [comment]
Thank you for your reply, I will double check the email address immediately and send my results to you again, thank you very much，i will send to the address :yyu@eecs.berkeley.edu   and    hongyanz@ttic.edu

**Comment by liuye6666** [comment]
I have check the address and  sent my results to you , my address is :liuye_ly94@163.com . If you have received my email, please let me know, I look forward to your reply.
