### ISSUE TITLE
A reminder for the submitted results of CAA

### ISSUE THREAD

**Issue by vtddggg** [yaodongyu/TRADES#21]
Hi, Dear Hongyang Zhang and Yaodong Yu,

This is a reminder that I have submitted our results(CAA) on TRADES White-box leaderboard. I have sent e-mail to your address. The issue can be closed once you have check the mailbox and no other problems occurred.
Feeling sorry to interrupt you and I would be grateful for your help. Thanks.

Xiaofeng Mao

**Comment by yaodongyu** [comment]
Updated. Thanks for your interest in our challenge.

Best,
Yaodong
