### ISSUE TITLE
Code running slow

### ISSUE THREAD

**Issue by alldbi** [yaodongyu/TRADES#25]
Hi, 

Thank you for providing the code and cheers to the great work!

I am training the model on CIFAR-10 using an NVIDIA Titan RTX-24G gpu. Unfortunately, the code is prohibitively slow and each iteration tasks about 4 seconds. Does it run at the same speed on your machine? The  WRN model is several times larger than an ordinary classifier for CIFAR-10. I know that the model for adv training should be large, but is it necessary to use such a huge model? 

Regards,
Ali

**Comment by yaodongyu** [comment]
Hi Ali,

I think the running speed of the code is okay on my end. For example, one epoch takes ~15 mins (using 2 GeForce RTX with batch_size = 128).
