### ISSUE TITLE
trades.py

### ISSUE THREAD

**Issue by liuye6666** [yaodongyu/TRADES#6]
I have read your article many times and feel that the article is well written, but I have a question. Should the sample be standardized to [0, 1]? Can it be standardized to [-1, 1]?why? Thank you very much,。

**Comment by hongyanz** [comment]
Thanks for your interests in our paper. There is no requirement that the sample should be standardized to [0, 1] and it can be standardized to other ranges as well, although in our codes/experiments we choose the former one as the PyTorch standardizes samples to [0, 1] by default.
