### ISSUE TITLE
What is the self.sub_block1 in models/wideresnet.py ？

### ISSUE THREAD

**Issue by zdhNarsil** [yaodongyu/TRADES#7]
In the `wideresnet.py` I find there is a `self.sub_block1` in `WideResNet.__init__()`, but it doesn't appear in `forward()`.

**Comment by yaodongyu** [comment]
Thanks for proposing this.

The `self.sub_block1` is the same as `self.block1` in https://github.com/yaodongyu/TRADES/blob/a2183f3a173b57499f27adb9dca145fa85d8269f/models/wideresnet.py#L61, and `self.block1` appears in the `forward()`. 

The `self.sub_block1` is redundant and we will remove this later.
